language: java

branches:
  only:
    - master

os: linux
dist: trusty

cache:
  timeout: 180
  directories:
    - $HOME/.CommandBox

before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list

install:
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  - box install production=false

jobs:

  include:
    - stage: Lucee 4 Test
      script:
        - box server start cfengine=lucee@4
        - box testbox run outputFile=./test-reports/junit-lucee-4.xml reporter=junit

    - stage: Lucee 5 Test
      script:
        - box server start cfengine=lucee@5
        - box testbox run outputFile=./test-reports/junit-lucee-5.xml reporter=junit
