pool:
  vmImage: 'ubuntu-16.04'

# steps:
# - script: |
#     echo Starting the build
#     curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
#     unzip /tmp/box.zip -d /tmp/
#     chmod a+x /tmp/box
#     /tmp/box install production=false
#     /tmp/box server start cfengine=lucee@4
#     mkdir /tmp/results/
#     /tmp/box testbox run outputFile=testbox-lucee4.xml reporter=junit
#   displayName: 'Run TestBox Tests'
#   # env:
#     #  FIXINATOR_API_KEY: $(FIXINATOR_API_KEY)
# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '**/testbox-*.xml' 
#     testRunTitle: TestBox Tests
#     failTaskOnFailedTests: true
#   displayName: 'TestBox Results'


stages:
- stage: Test
  jobs:
  - job: Lucee4
    steps:
    - script: |
        echo Starting the build
        curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
        unzip /tmp/box.zip -d /tmp/
        chmod a+x /tmp/box
        /tmp/box install production=false
        /tmp/box server start cfengine=lucee@4
        mkdir /tmp/results/
        /tmp/box testbox run outputFile=testbox-lucee4.xml reporter=junit
  - job: Lucee5
    steps:
    - script: |
        echo Starting the build
        curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
        unzip /tmp/box.zip -d /tmp/
        chmod a+x /tmp/box
        /tmp/box install production=false
        /tmp/box server start cfengine=lucee@5
        mkdir /tmp/results/
        /tmp/box testbox run outputFile=testbox-lucee5.xml reporter=junit
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
