trigger:
- master

# image: ortussolutions/commandbox:lucee5-alpine

stages:
- stage: Test
  jobs:
  - job: Lucee4
    container:
      image: ortussolutions/commandbox
    steps:
    - bash: |
      which bash
      echo Testing on Lucee 4!
  - job: Lucee5
    container:
      image: ortussolutions/commandbox
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
