trigger:
- master

# image: ortussolutions/commandbox:lucee5-alpine

stages:
- stage: Test
  jobs:
  - job: Lucee4
    container:
      image: ortussolutions/commandbox
    steps:

    - bash: |
      which bash
      echo echo Testing on Lucee 4!
      box install production=false
      box server start cfengine=lucee@4
      box testbox run outputFile=./test-reports/junit-lucee-4.xml reporter=junit
  - job: Lucee5
    container:
      image: ortussolutions/commandbox
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
