trigger:
- master

# image: ortussolutions/commandbox:lucee5-alpine

stages:
- stage: Test
  jobs:
  - job: Lucee4
    container:
      image: ortussolutions/commandbox
    steps:
    - script: echo Testing on Lucee 4!
    - script: box install production=false
    - script: box server start cfengine=lucee@4
    - script: box testbox run outputFile=./test-reports/junit-lucee-4.xml reporter=junit
  - job: Lucee5
    container:
      image: ortussolutions/commandbox
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
